using System;
using System.Data;

namespace VM.Lab.Interfaces.Autofeeder
{
	/// <summary> 
	/// Blob Analyzer communication controller
	/// Types that implement this class will be detected and gives the implementer the ability to control the different Blob Analyzers
	/// </summary>
	public abstract class AutofeederControl : IDisposable
	{
		/// <summary>Implementer of autofeeder control commands</summary>
		protected IAutofeederControlListener _listener;

		/// <summary> Base class for autofeeder controller </summary>
		/// <param name="listener">Implementer of autofeeder control commands</param>
		public AutofeederControl(IAutofeederControlListener listener)
		{
			_listener = listener;
		}

		/// <summary>Tells the controller that the autofeeder has changed state</summary>
		public abstract void StateChanged(AutofeederState oldState, AutofeederState newState, string sampleId, DataTable result);

		/// <summary>
		/// The autofeeder will ask the external controller if it would like to specify subfolder for the blob collection
		/// null is interpreted as the foldername should be generated by the blob analyzer itself
		/// </summary>
		/// <param name="measurementStartTime">Time the start measurement command was retrieved</param>
		public abstract string GetBlobCollectionSubfolder(DateTime measurementStartTime);

		/// <summary>
		/// The autofeeder will ask the external controller if it would like to specify filename for the prediction result filename
		/// null should be interpreted as external controller has no clue, and the filename should be generated by the autofeeder by itself
		/// </summary>
		/// <param name="measurementStartTime">Time the start measurement command was retrieved.</param>
		public abstract string GetPredictionResultFilename(DateTime measurementStartTime);

		#region IDisposable Support
		private bool disposedValue = false; // To detect redundant calls

		/// <summary>
		/// Dispose duh
		/// </summary>
		/// <param name="disposing"></param>
		protected virtual void Dispose(bool disposing)
		{
			if (!disposedValue)
			{
				if (disposing)
				{
					
				}
				disposedValue = true;
			}
		}


		/// <summary>
		/// This code added to correctly implement the disposable pattern.
		/// </summary>
		public void Dispose()
		{
			// Do not change this code. Put cleanup code in Dispose(bool disposing) above.
			Dispose(true);
		}
		#endregion
	}
}
